export const NBA_CODE = {
  ATL: {
    name: "Atlanta Hawks",
    colors: ["#E03A3E", "#C1D32F"],
    conference: "East",
    division: "Southeast",
    logo_url: "./images/nba-atlanta-hawks-logo-300x300.png",
  },
  BOS: {
    name: "Boston Celtics",
    colors: ["#007A33", "#BA9653"],
    conference: "East",
    division: "Atlantic",
    logo_url: "./images/nba-boston-celtics-logo-300x300.png",
  },
  BKN: {
    name: "Brooklyn Nets",
    colors: ["#000000", "#FFFFFF"],
    conference: "East",
    division: "Atlantic",
    logo_url: "./images/nba-brooklyn-nets-logo-300x300.png",
  },
  CHA: {
    name: "Charlotte Hornets",
    colors: ["#00788C", "#1D1160"],
    conference: "East",
    division: "Southeast",
    logo_url: "./images/nba-charlotte-hornets-logo-300x300.png",
  },
  CHI: {
    name: "Chicago Bulls",
    colors: ["#CE1141", "#000000"],
    conference: "East",
    division: "Central",
    logo_url: "./images/nba-chicago-bulls-logo-300x300.png",
  },
  CLE: {
    name: "Cleveland Cavaliers",
    colors: ["#6F263D", "#FFB81C"],
    conference: "East",
    division: "Central",
    logo_url: "./images/Clevelan-Cavaliers-logo-2022-300x300.png",
  },
  DAL: {
    name: "Dallas Mavericks",
    colors: ["#00538C", "#002B5E"],
    conference: "West",
    division: "Southwest",
    logo_url: "./images/nba-dallas-mavericks-logo-300x300.png",
  },
  DEN: {
    name: "Denver Nuggets",
    colors: ["#0E2240", "#FEC524"],
    conference: "West",
    division: "Northwest",
    logo_url: "./images/nba-denver-nuggets-logo-2018-300x300.png",
  },
  DET: {
    name: "Detroit Pistons",
    colors: ["#C8102E", "#006BB6"],
    conference: "East",
    division: "Central",
    logo_url: "./images/nba-detroit-pistons-logo-300x300.png",
  },
  GS: {
    name: "Golden State Warriors",
    colors: ["#1D428A", "#FFC72C"],
    conference: "West",
    division: "Pacific",
    logo_url: "./images/nba-golden-state-warriors-logo-2020-300x300.png",
  },
  HOU: {
    name: "Houston Rockets",
    colors: ["#CE1141", "#000000"],
    conference: "West",
    division: "Southwest",
    logo_url: "./images/nba-houston-rockets-logo-2020-300x300.png",
  },
  IND: {
    name: "Indiana Pacers",
    colors: ["#002D62", "#FDBB30"],
    conference: "East",
    division: "Central",
    logo_url: "./images/nba-indiana-pacers-logo-300x300.png",
  },
  LAC: {
    name: "LA Clippers",
    colors: ["#C8102E", "#1D428A"],
    conference: "West",
    division: "Pacific",
    logo_url: "./images/nba-la-clippers-logo-300x300.png",
  },
  LAL: {
    name: "Los Angeles Lakers",
    colors: ["#552583", "#FDB927"],
    conference: "West",
    division: "Pacific",
    logo_url: "./images/nba-los-angeles-lakers-logo-300x300.png",
  },
  MEM: {
    name: "Memphis Grizzlies",
    colors: ["#5D76A9", "#12173F"],
    conference: "West",
    division: "Southwest",
    logo_url: "./images/nba-memphis-grizzlies-logo-300x300.png",
  },
  MIA: {
    name: "Miami Heat",
    colors: ["#98002E", "#F9A01B"],
    conference: "East",
    division: "Southeast",
    logo_url: "./images/nba-miami-heat-logo-300x300.png",
  },
  MIL: {
    name: "Milwaukee Bucks",
    colors: ["#00471B", "#EEE1C6"],
    conference: "East",
    division: "Central",
    logo_url: "./images/nba-milwaukee-bucks-logo-300x300.png",
  },
  MIN: {
    name: "Minnesota Timberwolves",
    colors: ["#0C2340", "#78BE20"],
    conference: "West",
    division: "Northwest",
    logo_url: "./images/nba-minnesota-timberwolves-logo-300x300.png",
  },
  NO: {
    name: "New Orleans Pelicans",
    colors: ["#0C2340", "#C8102E"],
    conference: "West",
    division: "Southwest",
    logo_url: "./images/nba-new-orleans-pelicans-logo-300x300.png",
  },
  NY: {
    name: "New York Knicks",
    colors: ["#006BB6", "#F58426"],
    conference: "East",
    division: "Atlantic",
    logo_url: "./images/nba-new-york-knicks-logo-300x300.png",
  },
  OKC: {
    name: "Oklahoma City Thunder",
    colors: ["#007AC1", "#EF3B24"],
    conference: "West",
    division: "Northwest",
    logo_url: "./images/nba-oklahoma-city-thunder-logo-300x300.png",
  },
  ORL: {
    name: "Orlando Magic",
    colors: ["#0077C0", "#C4CED4"],
    conference: "East",
    division: "Southeast",
    logo_url: "./images/nba-orlando-magic-logo-300x300.png",
  },
  PHI: {
    name: "Philadelphia 76ers",
    colors: ["#006BB6", "#ED174C"],
    conference: "East",
    division: "Atlantic",
    logo_url: "./images/nba-philadelphia-76ers-logo-300x300.png",
  },
  PHO: {
    name: "Phoenix Suns",
    colors: ["#1D1160", "#E56020"],
    conference: "West",
    division: "Pacific",
    logo_url: "./images/nba-phoenix-suns-logo-300x300.png",
  },
  POR: {
    name: "Portland Trail Blazers",
    colors: ["#E03A3E", "#000000"],
    conference: "West",
    division: "Northwest",
    logo_url: "./images/nba-portland-trail-blazers-logo-300x300.png",
  },
  SAC: {
    name: "Sacramento Kings",
    colors: ["#5A2D81", "#63727A"],
    conference: "West",
    division: "Pacific",
    logo_url: "./images/nba-sacramento-kings-logo-300x300.png",
  },
  SA: {
    name: "San Antonio Spurs",
    colors: ["#C4CED4", "#000000"],
    conference: "West",
    division: "Southwest",
    logo_url: "./images/nba-san-antonio-spurs-logo-300x300.png",
  },
  TOR: {
    name: "Toronto Raptors",
    colors: ["#CE1141", "#000000"],
    conference: "East",
    division: "Atlantic",
    logo_url: "./images/nba-toronto-raptors-logo-2020-300x300.png",
  },
  UTA: {
    name: "Utah Jazz",
    colors: ["#002B5C", "#00471B"],
    conference: "West",
    division: "Northwest",
    logo_url: "./images/utah-jazz-logo-2022-300x300.png",
  },
  WAS: {
    name: "Washington Wizards",
    colors: ["#002B5C", "#E31837"],
    conference: "East",
    division: "Southeast",
    logo_url: "./images/nba-washington-wizards-logo-300x300.png",
  },
};

const playerExampleRes = {
  id: 1858,
  firstname: "Bruno",
  lastname: "Fernando",
  birth: { date: "1998-08-15", country: "Angola" },
  nba: { start: 2019, pro: 2 },
  height: { feets: "6", inches: "9", meters: "2.06" },
  weight: { pounds: "240", kilograms: "108.9" },
  college: "Maryland",
  affiliation: "Maryland/Angola",
  leagues: { standard: { jersey: 20, active: true, pos: "F-C" } },
  vegas: { jersey: 55, active: true, pos: "F-C" },
};

export const EAST_DIVISIONS = {
  atlantic: "Atlantic",
  central: "Central",
  southeast: "Southeast",
};
export const WEST_DIVISIONS = {
  northwest: "Northwest",
  pacific: "Pacific",
  southwest: "Southwest",
};

export const ALL_DIVISIONS = { ...EAST_DIVISIONS, ...WEST_DIVISIONS };
